#Switches#
- platform: mqtt
  name: "Perfect Prep"
  state_topic: "smartthings/Perfect Prep/switch/state"
  command_topic: "smartthings/Perfect Prep/switch/set"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  optimistic: false
  retain: false

- platform: mqtt
  name: "Living Room Scentsy"
  state_topic: "stat/livingroom_scentsy/POWER"
  command_topic: "cmnd/livingroom_scentsy/power"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 0
  optimistic: false
  retain: true

- platform: mqtt
  name: "Bedroom Scentsy"
  state_topic: "stat/bedroom_scentsy/POWER"
  command_topic: "cmnd/bedroom_scentsy/power"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 0
  optimistic: false
  retain: true

- platform: command_line
  switches:
    camera_record:
      command_on: !secret camera_record
      command_off: !secret camera_stop
      friendly_name: Camera's Recording


#- platform: tplink
#  name: "Smart Plug 3"
#  host: 192.168.1.129

#- platform: tplink
#  name: "Smart Plug 2"
#  host: 192.168.1.128

#- platform: tplink
#  name: "Smart Plug 1"
#  host: 192.168.1.130



- platform: broadlink
  host: 192.168.1.164
  mac: 34:EA:34:8E:E9:59
  friendly_name: Upstairs IR Sender
  timeout: 15
  switches:
    upstairs_tv_power:
      friendly_name: "Upstairs TV Power"
      command_on: 'JgBQAAABKJIUEBQREzYVEBMSExETEhMSEzYUNRMSEzYUNRQ2FDUTNhUQExITEhI3ExISEhMSExISNhQ2FDUUERM2EzYUNhQ1FAAFHgABKEkTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKJIUEBQREzYVEBMSExETEhMSEzYUNRMSEzYUNRQ2FDUTNhUQExITEhI3ExISEhMSExISNhQ2FDUUERM2EzYUNhQ1FAAFHgABKEkTAA0FAAAAAAAAAAA='
    upstairs_tv_volume:
      friendly_name: "Upstairs TV Volume"
      command_on: 'JgBQAAABJZURFBETETgRFBMSEhMSEhITETgSNxEUEjcTNhM3ETgROBQREzYUEREUExEUERMSExERORMSEDkQORQ1FTQUNhE4FQAFHgABJkoRAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJZUUEBMSEjcVEBITEhIRFBMSETgUNRUQETgVNBQ2FDUVNBM3EzYSExETERQSExETExISEhURETcVNRM2FTQRORA5FQAFHQABJUwQAA0FAAAAAAAAAAA='
    upstairs_tv_eco:
      friendly_name: "Upstairs TV Eco Mode"
      command_on: 'JgBYAAABJZUQFBUQETgVEBEUEBQRFBEUEDkROBEUETgROBE5FDUVNBE5FBATNhQSEDgVEBEUETgVEBE4FRAQORUQEDkROBUQEQAFIwABJ0kVAAxIAAElTBQADQU='
      command_off: 'JgBYAAABJZUQFBUQETgVEBEUEBQRFBEUEDkROBEUETgROBE5FDUVNBE5FBATNhQSEDgVEBEUETgVEBE4FRAQORUQEDkROBUQEQAFIwABJ0kVAAxIAAElTBQADQU='
    upstairs_tv_right:
      friendly_name: "Upstairs TV Right-Left"
      #Left#
      command_on: 'JgBYAAABJZUTERQREjcRFBMSEBQRFBITEDkTNhEUEzYTNxA5EzYTNhE5EzYROBMSERQTERQQEhQQFBMSExITNhE4FDUUNhE4EQAFIwABJ0oTAAxJAAElTBEADQU='
      #Right#
      command_off: 'JgBYAAABJZURFBETFDYRExMSERQRExQRETgTNxETEzcTNhE4ETgTNxETETkROBEUEhITEhEUERMRORETERQROBE4ETkROBE4EwAFIgABJUsRAAxMAAElSxEADQU='
    upstairs_tv_up:
      friendly_name: "Upstairs TV Up-Down"
      #Up#
      command_on: 'JgBQAAABJZUSExISETgUEREUERMRFBMSETgTNhEUETgUNhE4ETgUNREUExIRExEUExIRExE5ERMRORE4ETgROBI4EjcRFBE4FAAFIAABKEkRAA0FAAAAAAAAAAA='
      #Down#
      command_off: 'JgBQAAABJZUUERAVEDgUERQRERQTEhAUETgUNRQRFDURORQ1ETgUNRQ2ExEUEhAUEhIRFBE4ERQRFBM2ETgVNRM2ETgVEBE4EQAFIwABJUwRAA0FAAAAAAAAAAA='
