##############################################################################
###  All the house's motion sensors
##############################################################################

#################################################################
##   Motion Sensor in the Under Stairs Cupboard
#################################################################

- platform: mqtt
  name: "Motion Under Stairs Cupboard"
  state_topic: "smartthings/Hall Motion Sensor/motion/state"
  command_topic: "smartthings/Hall Motion Sensor/motion/state"
  device_class: motion
  payload_on: "active"
  payload_off: "inactive"
  retain: true

#################################################################
##   Motion Sensor in the Living Room
#################################################################

- platform: mqtt
  name: "Motion Living Room"
  state_topic: "smartthings/Living Room Motion/motion/state"
  command_topic: "smartthings/Living Room Motion/motion/state"
  device_class: motion
  payload_on: "active"
  payload_off: "inactive"
  retain: true

#################################################################
##   Motion Sensor in the Bedroom
#################################################################

- platform: mqtt
  name: "Motion Bedroom"
  state_topic: "smartthings/Bedroom Motion/motion/state"
  command_topic: "smartthings/Bedroom Motion/motion/state"
  device_class: motion
  payload_on: "active"
  payload_off: "inactive"
  retain: true

#################################################################
##   Motion Sensor in Hallway
#################################################################

- platform: mqtt
  name: "Motion Hallway"
  state_topic: "smartthings/Motion Sensor 1/motion/state"
  command_topic: "smartthings/Motion Sensor 1/motion/state"
  device_class: motion
  payload_on: "active"
  payload_off: "inactive"
  retain: true

#################################################################
##   Motion Sensor in Dressing Room
#################################################################

- platform: mqtt
  name: "Motion Dressing Room"
  state_topic: "smartthings/Xiaomi Motion 2/motion/state"
  command_topic: "smartthings/Xiaomi Motion 2/motion/state"
  device_class: motion
  payload_on: "active"
  payload_off: "inactive"
  retain: true
