homeassistant:
  name: Orchard Cottages
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 74
  unit_system: metric
  time_zone: Europe/London
  packages: !include_dir_named packages
  customize: !include_dir_merge_named customize

recorder:
config:
map:
updater:
conversation:
history:
logbook:
sun:
custom_updater:

mqtt:
  discovery: true
  discovery_prefix: homeassistant

http:
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key
  api_password: !secret http_password
  # base_url: !secret http_base_url
  # login_attempts_threshold: 3


# Discover some devices automatically
# discovery:
#  ignore:
#   - sabnzbd

tts:
  - platform: google

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    waypoint_whitelist:
      - Jack

  - platform: nmap_tracker
    hosts: !secret nmap
    exclude:
      - !secret nmap_exclude


ifttt:
  key: !secret ifttt

influxdb:
  host: 192.168.1.124
  port: 8086


#sonos
#media_player:
# - platform: sonos
#    scan_interval:  40


google:
  client_id: !secret google_id
  client_secret: !secret google_secret


group: !include groups.yaml
logger: !include logger.yaml
frontend: !include frontend.yaml
