name: Orchard Cottages
views:
- tab_icon: mdi:home
  name: Home
  cards:
    - type: picture-glance
      image: https://www.worcester.ac.uk/content_images/primary-outdoor-education-university-worcester-course-page-header.jpg
      title: Outdoors
      url: https://google.com/
      link: https://google.com/
      entities:
        - binary_sensor.motion_front_door
        - switch.garden_lights_temp
        - camera.front_door


# "zones"
# outdoor
# kitchen
# living Room
# front Room
# bedroom
# spare Room
# Circulation areas

    - type: camera-preview
      entity: camera.front_door
    - type: entities
      title: Home
      entities:
        - sensor.last_motion
        - sensor.jack_home_to_work
        - sensor.recycling_pickup_day
        - sensor.rubbish_pickup_day
    - type: entities
      title: Birthdays
      entities:
        - input_label.jack_birthday_days2go
        - input_label.lara_birthday_days2go
        - input_label.mollie_birthday_days2go
        - input_label.kitten_birthday_days2go
    - type: plant-status
      entity: plant.bathroom_plant
    - type: entities
      title: Vacuum
      entities:
        - vacuum.xiaomi_vacuum_cleaner
    - type: entities
      title: Circulation Lights
      entities:
        - light.hallway_light
        - light.pantry_lights
        - light.bathroom_lights
        - switch.garden_lights_temp
    - type: entities
      title: Climate
      entities:
        - climate.kitchen
    - type: media-control
      entity: media_player.shed_speaker
    - type: weather-forecast
      entity: weather.yahoo_home


- tab_icon: mdi:pot-mix
  name: Kitchen
  cards:
    - type: media-control
      entity: media_player.kitchen_speaker
    - type: camera-preview
      entity: camera.kitchen
    - type: entities
      title: Dishwasher
      entities:
        - input_select.dishwasher_status
    - type: entities
      title: Motion
      entities:
        - binary_sensor.motion_kitchen



- tab_icon: mdi:sofa
  name: Living Room
  cards:
    - type: entities
      title: Lights
      entities:
        - light.living_room_lamp
        - light.living_room_main_light
        - light.living_room_side_lights
    - type: camera-preview
      entity: camera.living_room
    - type: glance
      title: Living Room
      entities:
        - binary_sensor.motion_under_stairs_cupboard
        - binary_sensor.motion_living_room_camera
        - switch.scentsy_living_room
    - type: media-control
      entity: media_player.living_room_speaker
    - type: media-control
      entity: media_player.living_room_fire_tv
    - type: media-control
      entity: media_player.living_room_tv

- tab_icon: mdi:television
  name: Front Room
  cards:
    - type: media-control
      entity: media_player.front_room_speaker
    - type: media-control
      entity: media_player.front_room_tv
    - type: glance
      title: Front Room
      entities:
        - binary_sensor.motion_under_stairs_cupboard
        - binary_sensor.motion_living_room_camera
        - switch.scentsy_living_room
    - type: entities
      title: Lights
      entities:
        - light.front_room_main_light

- tab_icon: mdi:hotel
  name: Bedroom
  cards:
    - type: media-control
      entity: media_player.bedroom_fire_tv
    - type: media-control
      entity: media_player.bedroom_tv
    - type: media-control
      entity: media_player.bedroom_speaker
    - type: entities
      title: Bedroom
      entities:
        - light.bedroom_main_light
        - light.jack_bedside_light
        - light.lara_bedside_light
        - binary_sensor.motion_bedroom
        - switch.power_bedroom_humidifier
        - switch.scentsy_bedroom
    - type: entities
      title: Bedisde Lights
      entities:
        - light.jack_bedside_light
        - light.lara_bedside_light
    - type: entities
      title: Dressing Room
      entities:
        - light.dressing_room
        - binary_sensor.motion_dressing_room









- tab_icon: mdi:settings
  name: Settings
