name: Orchard Cottages
views:
- icon: mdi:home
  title: Home
  cards:
    - type: picture-glance
      image: https://www.worcester.ac.uk/content_images/primary-outdoor-education-university-worcester-course-page-header.jpg
      title: Outdoors
      entities:
        - binary_sensor.motion_front_door
        - switch.garden_lights_temp
        - camera.front_door
    - type: picture-glance
      image: https://www.homebase.co.uk/-/media/uk%20images/homebase/kitchens/steamer/steamer_earl_grey_highres_832x544.jpg
      title: Kitchen
      entities:
        - binary_sensor.motion_kitchen
        - climate.kitchen
        - input_select.dishwasher_status
    - type: picture-glance
      image: https://ksassets.timeincuk.net/wp/uploads/sites/56/2017/12/grey-neutral-living-room-1920x1152.jpg
      title: Living Room
      entities:
        - light.living_room_side_lights
        - camera.living_room
        - switch.living_room_scentsy_relay
        - binary_sensor.motion_living_room_camera
    - type: picture-glance
      image: https://st.hzcdn.com/simgs/4602895305854f2b_8-9930/home-design.jpg
      title: Front Room
      entities:
        - light.front_room_main_light
    - type: picture-glance
      image: https://images2.roomstogo.com/is/image/roomstogo/br_rm_belmar_black_pan~Belmar-Black-5-Pc-Queen-Bedroom.jpeg?$pdp_gallery_945$
      title: Bedroom
      entities:
        - binary_sensor.motion_bedroom
        - switch.power_bedroom_humidifier
        - switch.scentsy_bedroom
        - light.bedroom_main_light

    - type: vertical-stack
      cards:
        - type: camera-preview
          entity: camera.front_door
        - type: entities
          title: Motion Front Door
          entities: binary_sensor.motion_front_door
        - type: camera-preview
          entity: camera.kitchen
        - type: entities
          title: Motion Kitchen
          entities: binary_sensor.motion_kitchen

# "zones"
# outdoor
# kitchen
# living Room
# front Room
# bedroom
# spare Room
# Circulation areas

    - type: camera-preview
      entity: camera.front_door
    - type: entities
      title: Home
      entities:
        - sensor.last_motion
        - sensor.jack_home_to_work
        - sensor.recycling_pickup_day
        - sensor.rubbish_pickup_day
    - type: entities
      title: Birthdays
      entities:
        - input_label.jack_birthday_days2go
        - input_label.lara_birthday_days2go
        - input_label.mollie_birthday_days2go
        - input_label.kitten_birthday_days2go
    - type: plant-status
      entity: plant.bathroom_plant
    - type: entities
      title: Vacuum
      show_header_toggle: false
      entities:
        - vacuum.xiaomi_vacuum_cleaner
    - type: entities
      title: Circulation Lights
      show_header_toggle: true
      entities:
        - light.hallway_light
        - light.pantry_lights
        - light.bathroom_lights
        - light.garden_light
    - type: entities
      title: Climate
      entities:
        - climate.kitchen
    - type: media-control
      entity: media_player.shed_speaker
    - type: weather-forecast
      entity: weather.yahoo_home


- icon: mdi:pot-mix
  title: Kitchen
  cards:
    - type: media-control
      entity: media_player.kitchen_speaker
    - type: camera-preview
      entity: camera.kitchen
    - type: entities
      title: Dishwasher
      entities:
        - input_select.dishwasher_status
    - type: entities
      title: Motion
      entities:
        - binary_sensor.motion_kitchen



- icon: mdi:sofa
  title: Living Room
  cards:
    - type: entities
      title: Lights
      entities:
        - light.living_room_lamp
        - light.living_room_main_light
        - light.living_room_side_lights
    - type: camera-preview
      entity: camera.living_room
    - type: glance
      title: Living Room
      entities:
        - binary_sensor.motion_under_stairs_cupboard
        - binary_sensor.motion_living_room_camera
        - switch.living_room_scentsy_relay
    - type: media-control
      entity: media_player.living_room_speaker
    - type: media-control
      entity: media_player.living_room_fire_tv
    - type: media-control
      entity: media_player.living_room_tv

- icon: mdi:television
  title: Front Room
  cards:
    - type: media-control
      entity: media_player.front_room_speaker
    - type: media-control
      entity: media_player.front_room_tv
    - type: entities
      title: Lights
      entities:
        - light.front_room_main_light

- icon: mdi:hotel
  title: Bedroom
  cards:
    - type: media-control
      entity: media_player.bedroom_fire_tv
    - type: media-control
      entity: media_player.bedroom_tv
    - type: media-control
      entity: media_player.bedroom_speaker
    - type: entities
      title: Bedroom
      entities:
        - light.bedroom_main_light
        - light.jack_bedside_light
        - light.lara_bedside_light
        - binary_sensor.motion_bedroom
        - switch.power_bedroom_humidifier
        - switch.scentsy_bedroom
    - type: entities
      title: Bedisde Lights
      entities:
        - light.jack_bedside_light
        - light.lara_bedside_light
    - type: entities
      title: Dressing Room
      entities:
        - light.dressing_room
        - binary_sensor.motion_dressing_room



- icon: mdi:settings
  title: Settings
  cards:
  - type: entity-filter
    filter:
      - entity_id: '*battery*'
    card:
      type: entities
      title: Battery
