

- platform: mqtt
  name: "Bedroom Main Light"
  state_topic: "smartthings/Bedroom Main Light/switch/state"
  command_topic: "smartthings/Bedroom Main Light/switch/set"
  brightness_state_topic: "smartthings/Bedroom Main Light/level/state"
  brightness_command_topic: "smartthings/Bedroom Main Light/level/set"
  brightness_scale: 101
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false


- platform: mqtt
  name: "Front Room Main Light"
  state_topic: "smartthings/Front Room Main Light/switch/state"
  command_topic: "smartthings/Front Room Main Light/switch/set"
  brightness_state_topic: "smartthings/Front Room Main Light/level/state"
  brightness_command_topic: "smartthings/Front Room Main Light/level/set"
  brightness_scale: 101
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false


- platform: mqtt
  name: "Living Room Main Light"
  state_topic: "smartthings/Living Room Main Light/switch/state"
  command_topic: "smartthings/Living Room Main Light/switch/set"
  brightness_state_topic: "smartthings/Living Room Main Light/level/state"
  brightness_command_topic: "smartthings/Living Room Main Light/level/set"
  brightness_scale: 101
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false


- platform: group
  name: Bedside Lights
  entities:
    - light.jack_bedside_light
    - light.lara_bedside_light

- platform: group
  name: Living Room Side Lights
  entities:
    - light.living_room_side_light_1
    - light.living_room_side_light_2
