#################################################################
## lighting Automations
#################################################################



#################################################################
## Audio Prompts
#################################################################

      #################################################################
      ## Welcoming Homes
      #################################################################

#- alias: Welcome Home Lara
#  trigger:
#    - platform: state
#      entity_id: device_tracker.lara_lara
#      to: 'home'
#  action:
#    - service: script.sonos_say
#      data_template:
#        sonos_entity: media_player.kitchen
#        volume: 0.5
#        message: 'Welcome Home Lara'
#        delay: '00:00:10'

#- alias: Welcome Home Jack
#  trigger:
#    - platform: state
#      entity_id: device_tracker.jack_jack
#      to: 'home'
#  action:
#    - service: script.sonos_say
#      data_template:
#        sonos_entity: media_player.kitchen
#        volume: 0.5
#        message: 'Welcome Home Jack'
#        delay: '00:00:10'


#  action:
#    - service: tts.google_say
#      entity_id:
#        - media_player.kitchen
#      data_template:
#        message: >
#          {% if as_timestamp(now()) - as_timestamp(states.device_tracker.jack_jack.last_changed) < 300 and as_timestamp(now()) - as_timestamp(states.device_tracker.lara_lara.last_changed) < 300%}
#          Welcome home Jack and Lara!
#          {% elif as_timestamp(now()) - as_timestamp(states.device_tracker.jack_jack.last_changed) < 300%}
#          Welcome home Jack!
#          {% elif as_timestamp(now()) - as_timestamp(states.device_tracker.lara_lara.last_changed) < 300%}
#          Welcome home Lara!
#          {% else %}
#          This automation is confused!
#          {% endif %}




#################################################################
## Misc
#################################################################



#################################################################
## Stop bedroom white noise in the morning
#################################################################

- alias: stop white noise
  trigger:
    platform: time
    at: '06:45:00'
  action:
    - service: media_player.media_stop
      entity_id: media_player.bedroom_speaker


#################################################################
## Occupancy Automations
#################################################################

      #################################################################
      ## Living Room Occupancy
      #################################################################

- alias: Occupancy - Living turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_living_room_camera
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.living_occupancy

      #################################################################
      ## Reset Living Room Occupancy
      #################################################################

- alias: Occupancy - Living turn off after 30min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_living_room_camera
      to: 'off'
      for:
        minutes: 30
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_occupancy

      #################################################################
      ## Kitchen Occupancy
      #################################################################

- alias: Occupancy - Kitchen turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen_camera
      from: 'off'
      to: 'no'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.kitchen_occupancy

      #################################################################
      ## Reset Kitchen Occupancy
      #################################################################

- alias: Occupancy - Kitchen turn off after 30min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen_camera
      to: 'off'
      for:
        minutes: 30
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.kitchen_occupancy



#################################################################
## Heating Automation
#################################################################

      #################################################################
      ## Eco Mode Off
      #################################################################

#- alias: Heating Eco Mode On
#  trigger:
#    - platform: state
#      entity_id: device_tracker.jack_jack
#      to: 'home'
#    - platform: state
#      entity_id: device_tracker.lara_lara
#      to: 'home'
#  action:
#    - service: climate.set_operation_mode
#      data:
#        entity_id: climate.kitchen
#        operation_mode: heat

      #################################################################
      ## Eco Mode On
      #################################################################

#- alias: Heating Eco Mode Off
#  trigger:
#    - platform: state
#      entity_id: device_tracker.jack_jack
#      from: 'home'
#    - platform: state
#      entity_id: device_tracker.lara_lara
#      from: 'home'
#  action:
#    - service: climate.set_operation_mode
#      data:
#        entity_id: climate.kitchen
#        operation_mode: eco






- alias: Bedroom Idle
  trigger:
  - entity_id: binary_sensor.motion_bedroom
    for:
      minutes: 30
    from: 'On'
    platform: state
    to: 'Off'
  action:
  - data:
      entity_id: input_boolean.bedroom_idle
    service: input_boolean.turn_on

- alias: Living Room Idle
  trigger:
  - entity_id: binary_sensor.motion_living_room
    for:
      minutes: 30
    from: 'On'
    platform: state
    to: 'Off'
  action:
  - data:
      entity_id: input_boolean.living_room_idle
    service: input_boolean.turn_on

      #################################################################
      ## Reset input_boolean bedroom
      #################################################################

- alias: bedroom motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_bedroom
      from: 'Off'
      to: 'On'
  action:
  - data:
      entity_id: input_boolean.bedroom_idle
    service: input_boolean.turn_off

- alias: living room motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_living_room_camera
      from: 'Off'
      to: 'On'
  action:
  - data:
      entity_id: input_boolean.living_room_idle
    service: input_boolean.turn_off

      #################################################################
      ## set input_boolean bathroom
      #################################################################
#
# - alias: 'Bathroom Occupancy'
#   initial_state: 'off'
# #Trigger
#   trigger:
#     platform: state
#     entity_id: binary_sensor.door
#     from: 'off'
#     to: 'on'
#   condition:
#     condition: and
#     conditions:
# #motion ?
#       - condition: numeric_state
#         entity_id: sun.sun
#         value_template: '{{ state.attributes.elevation }}'
#         below: 10
#       - condition: time
#         after: '16:00:00'
#         before: '23:00:00'
#       - condition: state
#         entity_id: binary_sensor.motion_sensor_outside
#         state: 'on'
#   action:
#       - service: light.turn_off
#         entity_id: light.outside
#       - service: light.turn_on
#         entity_id: light.inside
#       - delay: 00:03:00
#       - service: light.turn_off
#         entity_id: light.inside
