##############################################################################
###  Turn the lights up slowly to help us wake up
##############################################################################

#################################################################
##   Weekday lights fade up
#################################################################

- alias: Weekday Wakeup
  trigger:
    platform: time
    at: '06:45:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: automation.turn_off
      entity_id: automation.detect_lights_and_adjust_the_brightness_when_turned_on_based_on_time
    - service: light.turn_on
      data:
        entity_id:
          - light.jack_bedside_light
          - light.lara_bedside_light
        transition: 900
        color_name: sandybrown
    - service: automation.turn_on
      entity_id: automation.detect_lights_and_adjust_the_brightness_when_turned_on_based_on_time


#################################################################
##   Weekend lights fade up
#################################################################


- alias: Weekend Wakeup
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: time
    weekday:
      - sun
      - sat
  action:
    - service: automation.turn_off
      entity_id: automation.detect_lights_and_adjust_the_brightness_when_turned_on_based_on_time
    - service: light.turn_on
      data:
        entity_id:
          - light.jack_bedside_light
          - light.lara_bedside_light
        transition: 900
        color_name: sandybrown
    - service: automation.turn_on
      entity_id: automation.detect_lights_and_adjust_the_brightness_when_turned_on_based_on_time
