##############################################################################
###  Detect when lights are turned on and adjust them accordingly based on time.
###  Code by @JesseWebDotCom
##############################################################################

- alias: auto adjust lights
  trigger:
    - platform: event
      event_type: state_changed
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.event.data.new_state.state == 'on' }}"
      - condition: template
        value_template: "{{ trigger.event.data.old_state.state == 'off' }}"
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ trigger.event.data.entity_id == 'light.dressing_room' }}"
          # - condition: template
          #   value_template: "{{ trigger.event.data.entity_id == 'light.bathroom_lights' }}"
          - condition: template
            value_template: "{{ trigger.event.data.entity_id == 'light.front_room_main_light' }}"
          - condition: template
            value_template: "{{ trigger.event.data.entity_id == 'light.hallway_light' }}"
          - condition: template
            value_template: "{{ trigger.event.data.entity_id == 'light.pantry_lights' }}"
          - condition: template
            value_template: "{{ trigger.event.data.entity_id == 'light.under_stairs_light' }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: "{{ trigger.event.data.entity_id }}"
        brightness: >
          {% set hour=states("sensor.time").split(':')[0] | int %}
          {%- if hour >= 5 and hour < 8  -%}
            80
          {%- elif hour >= 8 and hour <20  -%}
            255
          {%- elif hour >= 20 and hour <24  -%}
            80
          {%- else -%}
            15
          {%- endif %}
