##############################################################################
###  Maintain Brightness
##############################################################################
##############################################################################
#		As coded by @Skalavala and helped to completion by @Dale3h
#		Allows a room's brightness levels to be maintained,
#		regardless of number of lights turned on
##############################################################################


- alias: Maintain Brightness Bedroom
  trigger:
    - platform: state
      entity_id: light.bedroom_main_light
    - platform: state
      entity_id: light.jack_bedside_light
    - platform: state
      entity_id: light.lara_bedside_light
  action:
    - service_template: >-
        {% macro getlight_count() %}
          {% set count = 0 %}
          {% if is_state('light.bedroom_main_light', 'on') %}
            {% set count = count + 3 %}
          {% endif %}
          {% if is_state('light.jack_bedside_light', 'on') %}
            {% set count = count + 1 %}
          {% endif %}
          {% if is_state('light.lara_bedside_light', 'on') %}
            {% set count = count + 1 %}
          {% endif %}
          {{ count }}
        {% endmacro %}

        {% set count = getlight_count() %}
        {% if count == 0 %}
          light.turn_off
        {% else %}
          light.turn_on
        {% endif %}

#      data_template:
#        entity_id: >-
#          {% set comma = joiner() %}
#          {%- if is_state('light.bedroom_main_light', 'on') -%}
#            {{- comma() -}}
#            light.bedroom_main_light
#          {%- endif -%}
#          {%- if is_state('light.jack_bedside_light', 'on') -%}
#            {{- comma() -}}
#            light.jack_bedside_light
#          {%- endif -%}
#          {%- if is_state('light.lara_bedside_light', 'on') -%}
#            {{- comma() -}}
#            light.lara_bedside_light
#          {%- endif -%}

      data_template:
        entity_id: >-
          {% set lights = [
          	'light.bedroom_main_light',
            'light.jack_bedside_light',
            'light.lara_bedside_light'
          ] %}
          {% set comma = joiner(',') %}
          {%- for light in lights if is_state(light, 'on') -%}
            {{ comma() }}{{ light }}
          {%- endfor -%}

        brightness: >-
          {% macro getlight_count() %}
            {% set count = 0 %}
            {% if is_state('light.bedroom_main_light', 'on') %}
              {% set count = count + 3 %}
            {% endif %}
            {% if is_state('light.jack_bedside_light', 'on') %}
              {% set count = count + 1 %}
            {% endif %}
            {% if is_state('light.lara_bedside_light', 'on') %}
              {% set count = count + 1 %}
            {% endif %}
            {{ count }}
          {% endmacro %}

          {% set count = getlight_count()|int %}
          {% if count == 5 %}
            20
          {% elif count == 4 %}
            25
          {% elif count == 3 %}
            33
          {% elif count == 2 %}
            50
          {% elif count == 1 %}
            100
          {% else %}
            0
          {% endif %}
