##############################################################################
###  Set the default media_player (Google Homes) volume
##############################################################################

#################################################################
## Day Time Google Home Volume
#################################################################

- alias: Day Time Google Home Volume
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.bedroom_speaker
        - media_player.front_room_speaker
        - media_player.kitchen_speaker
        - media_player.living_room_speaker
        - media_player.shed_speaker
      data:
        volume_level: "0.45"

#################################################################
## Night Time Google Home Volume
#################################################################

- alias: Night Time Google Home Volume
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.bedroom_speaker
        - media_player.front_room_speaker
        - media_player.kitchen_speaker
        - media_player.living_room_speaker
        - media_player.shed_speaker
      data:
        volume_level: "0.09"
