##############################################################################
###  Morning Announcements to start off our day
##############################################################################

#################################################################
## Weekday Morning Greeting
#################################################################

- alias: 'Goodmorning Bedroom Weekday'
  trigger:
   platform: time
   at: '07:20:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker
        volume: 0.4
        message: 'Goodmorning Johnson Family. Time to get out of Bed! The Weather forcast is {{states.sensor.dark_sky_hourly_summary.state}}, the temperature outside is currently {{states.sensor.weather_temperature.state|round}} degrees, Jacks travel time to work currently is {{states.sensor.jack_home_to_work.state}} minutes'
#        message: 'Goodmorning Johnson Family. Time to get out of Bed! The Weather forcast is {{states.sensor.dark_sky_hourly_summary.state}}, the temperature outside is currently {{states.sensor.weather_temperature.state}} degrees, Jacks travel time to work currently is {{states.sensor.jack_home_to_work.state}} minutes and Laaras travel time to work currently is {{states.sensor.lara_home_to_work.state}} minutes'

        delay: '00:00:30'

#################################################################
## Weekend Morning Greeting
#################################################################

- alias: 'Goodmorning Bedroom Weekend'
  trigger:
   platform: time
   at: '08:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker
        volume: 0.4
        message: 'Goodmorning Johnson Family. Happy Weekend! The Weather forcast is {{states.sensor.dark_sky_hourly_summary.state}}, the temperature outside is currently {{states.sensor.weather_temperature.state|round}} degrees'
        delay: '00:00:30'

#################################################################
## Is It Riding Weather Today
#################################################################

- alias: Riding Weather
  trigger:
   platform: time
   at: '07:30:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.dark_sky_precip_probability
        below: 20
#        for:
#          hours: 12
#          minutes: 0
#          seconds: 0
      - condition: numeric_state
        entity_id: sensor.dark_sky_daily_low_temperature
        above: 6
      - condition: numeric_state
        entity_id: sensor.dark_sky_wind_speed
        below: 35
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker
        volume: 0.4
        message: 'How about taking the Motobike in today?'
        delay: '00:00:10'
