- platform: firetv
  device: Living_Room
  name: Living Room Fire TV

- platform: firetv
  device: Bedroom
  name: Bedroom Fire TV

- platform: firetv
  device: Front_Room
  name: Front Room Fire TV

- platform: cast
  name: Kitchen Google Assistant
  host: 192.168.1.203

- platform: cast
  name: Bedroom Google Assistant
  host: 192.168.1.242

- platform: cast
  name: Front Room Google Assistant
  host: 192.168.1.88

- platform: cast
  name: Living Room Google Assistant
  host: 192.168.1.124

#- platform: cast
#  name: Shed Google Assistant
#  host: 192.168.1.?

#- platform: firetv
#  device: Front_Room
#  name: Front Room Fire TV
#  ,
#    {
#      "name": "Front_Room",
#      "host": "192.168.1.254",
#      "port": 5555
#    }

- platform: braviatv
  host: 192.168.1.128
  name: Living Room TV

- platform: braviatv
  host: 192.168.1.237
  name: Front Room TV

#- platform: sonos
#  hosts:
#    - 192.168.1.250
#    - 192.168.1.131

#- platform: ps4
#  host: http://0.0.0.0:3031
#  ps4_ip: 192.168.1.252
#  name: PlayStation 4
#  local_store: games
