################################################################
## Packages / Morning Announcements
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Morning Announcements'

      expose: &expose
        <<: *customize
        expose: false

    ################################################
    ## Morning Announcements
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Morning Announcements - Automations
################################################

automation:

    #################################################################
    ## Feed the kittens notification's
    #################################################################


- alias: Feed the Lara lunch
  trigger:
    - platform: time
      at: '12:30:00'
  action:
    - service: script.google_notify
      data_template:
        message: 'Feed the Laara!'

    ##############################################################################
    ###  Audio notification to ramind us of kitten's food time
    ##############################################################################

- alias: Feed the kittens
  trigger:
    - platform: time
      at: '07:30:00'
    - platform: time
      at: '14:00:00'
    - platform: time
      at: '21:00:00'
  action:
    - service: script.google_notify
      data_template:
        message: 'Feed the Kittens!'

      #################################################################
      ## Weekday Morning Greeting
      #################################################################

- alias: 'Goodmorning Bedroom Weekday'
  trigger:
   platform: time
   at: '07:20:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker
        volume: 0.4
        message: 'Goodmorning Johnson Family. Time to get out of Bed! The Weather forcast is {{states.sensor.dark_sky_hourly_summary.state}}, the temperature outside is currently {{states.sensor.weather_temperature.state|round}} degrees, Jacks travel time to work currently is {{states.sensor.jack_home_to_work.state}} minutes'
        delay: '00:00:30'


      #################################################################
      ## Weekend Morning Greeting
      #################################################################

- alias: 'Goodmorning Bedroom Weekend'
  trigger:
   platform: time
   at: '08:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker
        volume: 0.4
        message: 'Goodmorning Johnson Family. Happy Weekend! The Weather forcast is {{states.sensor.dark_sky_hourly_summary.state}}, the temperature outside is currently {{states.sensor.weather_temperature.state|round}} degrees'
        delay: '00:00:30'

      #################################################################
      ## Is it Riding Weather Today
      #################################################################


- alias: Riding Weather
  trigger:
   platform: time
   at: '07:30:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.dark_sky_precip_probability
        below: 20
#        for:
#          hours: 12
#          minutes: 0
#          seconds: 0
      - condition: numeric_state
        entity_id: sensor.dark_sky_daily_low_temperature
        above: 6
      - condition: numeric_state
        entity_id: sensor.dark_sky_wind_speed
        below: 35
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker
        volume: 0.4
        message: 'How about taking the Motorbike in today?'
        delay: '00:00:10'


      #################################################################
      ## Welcoming Homes
      #################################################################

#- alias: Welcome Home Lara
#  trigger:
#    - platform: state
#      entity_id: device_tracker.lara_lara
#      to: 'home'
#  action:
#    - service: script.sonos_say
#      data_template:
#        sonos_entity: media_player.kitchen
#        volume: 0.5
#        message: 'Welcome Home Lara'
#        delay: '00:00:10'

#- alias: Welcome Home Jack
#  trigger:
#    - platform: state
#      entity_id: device_tracker.jack_jack
#      to: 'home'
#  action:
#    - service: script.sonos_say
#      data_template:
#        sonos_entity: media_player.kitchen
#        volume: 0.5
#        message: 'Welcome Home Jack'
#        delay: '00:00:10'


#  action:
#    - service: tts.google_say
#      entity_id:
#        - media_player.kitchen
#      data_template:
#        message: >
#          {% if as_timestamp(now()) - as_timestamp(states.device_tracker.jack_jack.last_changed) < 300 and as_timestamp(now()) - as_timestamp(states.device_tracker.lara_lara.last_changed) < 300%}
#          Welcome home Jack and Lara!
#          {% elif as_timestamp(now()) - as_timestamp(states.device_tracker.jack_jack.last_changed) < 300%}
#          Welcome home Jack!
#          {% elif as_timestamp(now()) - as_timestamp(states.device_tracker.lara_lara.last_changed) < 300%}
#          Welcome home Lara!
#          {% else %}
#          This automation is confused!
#          {% endif %}
