################################################################
## Packages / Batteries
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Batteries'
        device_class: battery

      expose: &expose
        <<: *customize
        expose: true

      not-expose: &not-expose
        <<: *customize
        expose: false

    ################################################
    ## Batteries - Motion Sensor
    ################################################

    sensor.motion_dressing_room_battery:
      <<: *customize
      friendly_name: "Battery - Motion Sensor - Dressing Room"

    sensor.motion_bedroom_battery:
      <<: *customize
      friendly_name: "Battery - Motion Sensor - Bedroom"


    ################################################
    ## Batteries - Door Sensor
    ################################################

    sensor.door_sensor_dishwasher:
      <<: *customize
      friendly_name: "Battery - Door Sensor - Dishwasher"

    sensor.door_sensor_bathroom:
      <<: *customize
      friendly_name: "Battery - Door Sensor - Bathroom"

    sensor.door_sensor_dressing_room_window:
      <<: *customize
      friendly_name: "Battery - Door Sensor - Dressing Room Window"

    ################################################
    ## Batteries - Door Sensor
    ################################################

    sensor.presence_sensor_jack_car:
      <<: *customize
      friendly_name: "Battery - Presence Sensor - Jack Car"

    sensor.presence_sensor_lara_car:
      <<: *customize
      friendly_name: "Battery - Presence Sensor - Lara Car"

################################################
## Batteries - Sensor
################################################

sensor:

    ################################################
    ## Motion Sensors
    ################################################

  - platform: mqtt
    name: battery_motion_dressing_room
    state_topic: "smartthings/Motion Dressing Room/battery/state"
    device_class: battery
    unit_of_measurement: '%'

  - platform: mqtt
    name: battery_motion_bedroom
    state_topic: "smartthings/Bedroom Motion/battery/state"
    device_class: battery
    unit_of_measurement: '%'

    ################################################
    ## Door Sensors
    ################################################

  - platform: mqtt
    name: battery_door_sensor_dishwasher
    state_topic: "smartthings/Door Sensor - Dishwasher/battery/state"
    device_class: battery
    unit_of_measurement: '%'

  - platform: mqtt
    name: battery_door_sensor_bathroom
    state_topic: "smartthings/Door Sensor - Bathroom/battery/state"
    device_class: battery
    unit_of_measurement: '%'

  - platform: mqtt
    name: battery_door_sensor_dressing_room_window
    state_topic: "smartthings/Door Sensor - Dressing Room Window/battery/state"
    device_class: battery
    unit_of_measurement: '%'

    ################################################
    ## Presence Sensors
    ################################################

  - platform: mqtt
    name: battery_presence_sensor_jack_car
    state_topic: "smartthings/Presence Jack Car/battery/state"
    device_class: battery
    unit_of_measurement: '%'

  - platform: mqtt
    name: battery_presence_sensor_lara_car
    state_topic: "smartthings/Presence Lara Car/battery/state"
    device_class: battery
    unit_of_measurement: '%'
