################################################################
## Packages / Bayesian
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Bayesian'

      expose: &expose
        <<: *customize
        expose: true

      not-expose: &not-expose
        <<: *customize
        expose: false

    ################################################
    ## Bayesian
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Bayesian - Binary Sensor's
################################################

binary_sensor:

      #################################################################
      ##   Bayesian Sensor for Sleeping
      #################################################################

# - platform: bayesian
#   name: Sleeping
#   prior: 0.3  # 30% chance that somebody is sleeping at any given moment
#   probability_threshold: 0.90
#   observations:
#     # All lights off -> likely we're asleep
#     # - entity_id: group.all_lights
#     #   platform: state
#     #   to_state: 'off'
#     #   prob_given_true: 0.80
#     #   prob_given_false: 0.10
#     # Somebody at home -> 40% change we're asleep
#     - entity_id: group.family
#       platform: state
#       to_state: home
#       prob_given_true: 0.30
#       prob_given_false: 0.01
#     #
#     - entity_id: sensor.motion_stairs
#       platform: state
#       to_state: 'off'
#       prob_given_true: 0.90
    # Somebody at home -> Very Likely motion will be detected

      #################################################################
      ##   Bayesian Sensor for Jack Home
      #################################################################

- platform: bayesian
  name: jack home
  prior: 0.4  # 60% chance that somebody is at home at any given moment
  probability_threshold: 0.90
  observations:
    # Somebody at home -> Very likely at least one household member is at home
    - entity_id: device_tracker.jack_phone
      platform: state
      to_state: 'home'
      prob_given_true: 0.90
      prob_given_false: 0.10
    # Somebody at home -> likely that at least one indoor light is turned on
    - entity_id: device_tracker.jack_smart_watch
      platform: state
      to_state: 'home'
      prob_given_true: 0.50
      prob_given_false: 0.50
    #
    - entity_id: device_tracker.jack_jack
      platform: state
      to_state: 'home'
      prob_given_true: 0.75
      prob_given_false: 0.25
    # Somebody at home -> Very Likely motion will be detected

      #################################################################
      ##   Bayesian Sensor for Lara Home
      #################################################################

- platform: bayesian
  name: lara home
  prior: 0.6  # 60% chance that somebody is at home at any given moment
  probability_threshold: 0.90
  observations:
    # Somebody at home -> Very likely at least one household member is at home
    - entity_id: device_tracker.lara_iphone
      platform: state
      to_state: 'home'
      prob_given_true: 0.90
      prob_given_false: 0.10
    # Somebody at home -> likely that at least one indoor light is turned on
    - entity_id: device_tracker.lara_lara
      platform: state
      to_state: 'home'
      prob_given_true: 0.60
      prob_given_false: 0.40
    # Somebody at home -> Very Likely motion will be detected

      #################################################################
      ##   Bayesian Sensor someone watching TV in Bedroom
      #################################################################

- platform: bayesian
  name: someone watching tv bedroom
  prior: 0.1  # 60% chance that somebody is at home at any given moment
  probability_threshold: 0.70
  observations:
    # Somebody at home -> Very likely at least one household member is at home
    - entity_id: group.family
      platform: state
      to_state: 'home'
      prob_given_true: 0.90
      prob_given_false: 0.10
    # Somebody at home -> likely that at least one indoor light is turned on
    - entity_id: media_player.bedroom_fire_tv
      platform: state
      to_state: 'playing'
      prob_given_true: 0.99
      prob_given_false: 0.01
    # Somebody at home -> likely that at least one indoor light is turned on
    - entity_id: input_boolean.bedroom_idle
      platform: state
      to_state: 'off'
      prob_given_true: 0.30
      prob_given_false: 0.20

      #################################################################
      ##   Bayesian Sensor someone watching TV in Living Room
      #################################################################

- platform: bayesian
  name: someone watching tv livingroom
  prior: 0.1  # 60% chance that somebody is at home at any given moment
  probability_threshold: 0.70
  observations:
    # Somebody at home -> Very likely at least one household member is at home
    - entity_id: group.family
      platform: state
      to_state: 'home'
      prob_given_true: 0.90
      prob_given_false: 0.10
    # Somebody at home -> likely that at least one indoor light is turned on
    - entity_id: media_player.living_room_fire_tv
      platform: state
      to_state: 'playing'
      prob_given_true: 0.99
      prob_given_false: 0.01
    # Somebody at home -> likely that at least one indoor light is turned on
    - entity_id: input_boolean.living_room_idle
      platform: state
      to_state: 'off'
      prob_given_true: 0.30
      prob_given_false: 0.20
