################################################################
## Packages / Blue Iris's
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'blueiris'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## Blue Iris - Cameras
    ################################################

    camera.driveway:
      <<: *customize
      friendly_name: "Driveway Camera"

    camera.kitchen:
      <<: *customize
      friendly_name: "Kitchen Camera"

    camera.lounge:
      <<: *customize
      friendly_name: "Lounge Camera"

    ################################################
    ## Blue Iris - Groups
    ################################################

    group.indoor:
      <<: *customize
      friendly_name: "Indoor Cameras"

    group.outdoor:
      <<: *customize
      friendly_name: "Outdoor Cameras"

    ################################################
    ## Blue Iris - Switch
    ################################################

    switch.camera_record:
      <<: *customize
      friendly_name: Camera's Recording

    ################################################
    ## Blue Iris - Automations
    ################################################

    automation.vacant_house_recording:
      <<: *customize
      friendly_name: Record when the house is empty


    automation.occupied_house_stop_recording:
      <<: *customize
      friendly_name: Stop recording when the house is occupied


    automation.overnight_camera_recording:
      <<: *customize
      friendly_name: Start recording over night

    automation.morning_camera_stop_recording:
      <<: *customize
      friendly_name: Stop recording in the morning

#################################################################
## Blue Iris - Automations
#################################################################

group:

      #################################################################
      ## Camera Indoors
      #################################################################

  cameras_indoor:
    control: hidden
    entities:
      - camera.kitchen
      - camera.lounge

      #################################################################
      ## Camera Outdoors
      #################################################################

  cameras_outdoor:
    control: hidden
    entities:
      - camera.driveway

################################################
## Camera - Camera's
################################################

camera:

      #################################################################
      ## Blue Iris Cameras
      #################################################################

- platform: mjpeg
  mjpeg_url: !secret blueiris_lounge_url
  name: Lounge
  username: !secret camera_user
  password: !secret camera_pass
  authentication: basic

- platform: mjpeg
  mjpeg_url: !secret blueiris_kitchen_url
  name: Kitchen
  username: !secret camera_user
  password: !secret camera_pass
  authentication: basic

################################################
## Blue Iris - Binary Sensor
################################################

# binary_sensor:

      #################################################################
      ## Recording binary_sensor
      #################################################################


# - platform: template
#   sensors:
#     camera_recording:
#       device_class: presence
#       value_template: "{{ is_state('switch.camera_record', 'on') }}"
#       friendly_name: 'Camera Recording'

################################################
## Blue Iris - Switches
################################################

switch:

      #################################################################
      ## Recording start/stop
      #################################################################

- platform: command_line
  switches:
    camera_record:
      command_on: !secret camera_record
      command_off: !secret camera_stop

#################################################################
## Camera - Automations
#################################################################

automation:

      #################################################################
      ## Camera recording
      #################################################################

- alias: vacant house recording
  trigger:
    - platform: state
      entity_id: device_tracker.jack_jack
      from: 'home'
    - platform: state
      entity_id: device_tracker.lara_lara
      from: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.camera_record

- alias: occupied house stop recording
  trigger:
    - platform: state
      entity_id: device_tracker.jack_jack
      to: 'home'
    - platform: state
      entity_id: device_tracker.lara_lara
      to: 'home'
  action:
    - service: switch.turn_off
      entity_id: switch.camera_record

- alias: overnight camera recording
  trigger:
    - platform: time
      at: '23:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.camera_record

- alias: morning camera stop recording
  trigger:
    - platform: time
      at: '06:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.camera_record
