################################################################
## Packages / Camera's
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Camera'

      expose: &expose
        <<: *customize
        expose: false

    ################################################
    ## Camera
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Camera - Camera's
################################################

camera:

      #################################################################
      ## Blue Iris Cameras
      #################################################################

- platform: mjpeg
  mjpeg_url: http://192.168.1.239:81/mjpg/kitchen2
  name: Kitchen2
  username: !secret camera_user
  password: !secret camera_pass
  authentication: basic

- platform: mjpeg
  mjpeg_url: http://192.168.1.239:81/mjpg/lounge
  name: Lounge
  username: !secret camera_user
  password: !secret camera_pass
  authentication: basic

- platform: mjpeg
  mjpeg_url: http://192.168.1.239:81/mjpg/kitchen
  name: Kitchen
  username: !secret camera_user
  password: !secret camera_pass
  authentication: basic


################################################
## Camera - Binary Sensor
################################################

binary_sensor:

      #################################################################
      ## Recording
      #################################################################


- platform: template
  sensors:
    camera_recording:
      device_class: presence
      value_template: "{{ is_state('switch.camera_record', 'on') }}"
      friendly_name: 'Camera Recording'

################################################
## Camera - Switches
################################################

switch:

      #################################################################
      ## Recording start/stop
      #################################################################

- platform: command_line
  switches:
    camera_record:
      command_on: !secret camera_record
      command_off: !secret camera_stop
      friendly_name: Camera's Recording

#################################################################
## Camera - Automations
#################################################################

automation:

      #################################################################
      ## Camera recording
      #################################################################

- alias: Start Camera Recording
  trigger:
    - platform: state
      entity_id: device_tracker.jack_jack
      from: 'home'
    - platform: state
      entity_id: device_tracker.lara_lara
      from: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.camera_record

- alias: Stop Camera Recording
  trigger:
    - platform: state
      entity_id: device_tracker.jack_jack
      to: 'home'
    - platform: state
      entity_id: device_tracker.lara_lara
      to: 'home'
  action:
    - service: switch.turn_off
      entity_id: switch.camera_record

- alias: Night Camera Recording
  trigger:
    - platform: time
      at: '23:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.camera_record

- alias: Morning Camera Recording
  trigger:
    - platform: time
      at: '06:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.camera_record
