################################################################
## Packages / Device Status
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Device Status'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## Device Status
    ################################################

    sensor.status_philips_hue_hub:
      <<: *expose
      friendly_name: Philips Hue Bridge
      entity_picture: /local/hue.png

    sensor.status_jack_laptop:
      <<: *expose
      friendly_name: Jacks Laptop
      entity_picture: /local/apple.png

    sensor.status_smart_thing_hub:
      <<: *expose
      friendly_name: Smart Things Hub
      entity_picture: /local/smartthings.png

    sensor.status_ps4:
      <<: *expose
      friendly_name: PS4
      entity_picture: /local/playstation.png

    sensor.status_fire_tv_1:
      <<: *expose
      friendly_name: Fire TV 1
      entity_picture: /local/firetv.png

    sensor.status_fire_tv_2:
      <<: *expose
      friendly_name: Fire TV 2
      entity_picture: /local/firetv.png

    sensor.status_fire_tv_3:
      <<: *expose
      friendly_name: Fire TV 3
      entity_picture: /local/firetv.png


################################################
## Device Status - Sensor
################################################

sensor:

      ################################################
      ## Device Status - Bedroom RF Transmitter
      ################################################

- platform: template
  sensors:
    status_bedroom_rf:
      friendly_name: 'Bedroom RF Transmitter'
      value_template: >-
        {% if is_state("device_tracker.bedroom_rf_transmitter", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.bedroom_rf_transmitter", "home") %}
          mdi:television-classic
        {% else %}
          mdi:television-classic-off
        {% endif %}

      ################################################
      ## Device Status - Fire TV 1
      ################################################

- platform: template
  sensors:
    status_fire_tv_1:
      friendly_name: 'Fire TV 1'
      value_template: >-
        {% if is_state("device_tracker.fire_tv_1", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}

      ################################################
      ## Device Status - Fire TV 2
      ################################################

- platform: template
  sensors:
    status_fire_tv_2:
      friendly_name: 'Fire TV 2'
      value_template: >-
        {% if is_state("device_tracker.fire_tv_2", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}

      ################################################
      ## Device Status - Fire TV 3
      ################################################

- platform: template
  sensors:
    status_fire_tv_3:
      friendly_name: 'Fire TV 3'
      value_template: >-
        {% if is_state("device_tracker.fire_tv_3", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}

      ################################################
      ## Device Status - Google Home Bedroom
      ################################################

- platform: template
  sensors:
    status_google_home_bedroom:
      friendly_name: 'Google Home - Bedroom'
      value_template: >-
        {% if is_state("device_tracker.google_home_bedroom", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.google_home_bedroom", "home") %}
          mdi:google-home
        {% else %}
          mdi:cancel
        {% endif %}

      ################################################
      ## Device Status - Google Home Front Room
      ################################################

- platform: template
  sensors:
    status_google_home_front_room:
      friendly_name: 'Google Home - Front Room'
      value_template: >-
        {% if is_state("device_tracker.google_home_front_room", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.google_home_front_room", "home") %}
          mdi:google-home
        {% else %}
          mdi:cancel
        {% endif %}

      ################################################
      ## Device Status - Google Home Kitchen
      ################################################

- platform: template
  sensors:
    status_google_home_kitchen:
      friendly_name: 'Google Home - Kitchen'
      value_template: >-
        {% if is_state("device_tracker.google_home_kitchen", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.google_home_kitchen", "home") %}
          mdi:google-home
        {% else %}
          mdi:cancel
        {% endif %}

      ################################################
      ## Device Status - Google Home Living Room
      ################################################

- platform: template
  sensors:
    status_google_home_living_room:
      friendly_name: 'Google Home - Living Room'
      value_template: >-
        {% if is_state("device_tracker.google_home_living_room", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.google_home_living_room", "home") %}
          mdi:google-home
        {% else %}
          mdi:cancel
        {% endif %}

      ################################################
      ## Device Status - Hikvision 1
      ################################################

- platform: template
  sensors:
    status_hikvision_1:
      friendly_name: 'Hikvision 1'
      value_template: >-
        {% if is_state("device_tracker.hikvision_1", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.hikvision_1", "home") %}
          mdi:cctv
        {% else %}
          mdi:cancel
        {% endif %}

      ################################################
      ## Device Status - Hikvision 2
      ################################################

- platform: template
  sensors:
    status_hikvision_2:
      friendly_name: 'Hikvision 2'
      value_template: >-
        {% if is_state("device_tracker.hikvision_2", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.hikvision_2", "home") %}
          mdi:cctv
        {% else %}
          mdi:cancel
        {% endif %}

      ################################################
      ## Device Status - Hikvision 3
      ################################################

- platform: template
  sensors:
    status_hikvision_3:
      friendly_name: 'Hikvision 3'
      value_template: >-
        {% if is_state("device_tracker.hikvision_3", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.hikvision_3", "home") %}
          mdi:cctv
        {% else %}
          mdi:cancel
        {% endif %}

      ################################################
      ## Device Status - Jacks Laptop
      ################################################

- platform: template
  sensors:
    status_jack_laptop:
      friendly_name: 'Jacks Laptop'
      value_template: >-
        {% if is_state("device_tracker.jack_laptop", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}

      ################################################
      ## Device Status - Media Server
      ################################################

- platform: template
  sensors:
    status_media_server:
      friendly_name: 'Media Server'
      value_template: >-
        {% if is_state("device_tracker.media_server", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.media_server", "home") %}
          mdi:server
        {% else %}
          mdi:cancel
        {% endif %}

      ################################################
      ## Device Status - Nest Camera
      ################################################

- platform: template
  sensors:
    status_nest_camera:
      friendly_name: 'Nest Camera'
      value_template: >-
        {% if is_state("device_tracker.nest_camera", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}

      ################################################
      ## Device Status - Nest Thermostat
      ################################################

- platform: template
  sensors:
    status_nest_thermostat:
      friendly_name: 'Nest Thermostat'
      value_template: >-
        {% if is_state("device_tracker.nest_thermostat", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}

      ################################################
      ## Device Status - Network Extender
      ################################################

- platform: template
  sensors:
    status_network_extender:
      friendly_name: 'Network Extender'
      value_template: >-
        {% if is_state("device_tracker.network_extender", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.network_extender", "home") %}
          mdi:wifi
        {% else %}
          mdi:wifi-off
        {% endif %}

      ################################################
      ## Device Status - Philips Hue Hub
      ################################################

- platform: template
  sensors:
    status_philips_hue_hub:
      friendly_name: 'Philips Hue Hub'
      value_template: >-
        {% if is_state("device_tracker.philips_hue_hub", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}

      ################################################
      ## Device Status - PS4
      ################################################

- platform: template
  sensors:
    status_ps4:
      friendly_name: 'PS4'
      value_template: >-
        {% if is_state("device_tracker.ps4", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}

      ################################################
      ## Device Status - Router - Kitchen
      ################################################

- platform: template
  sensors:
    status_unifi_kitchen_ap:
      friendly_name: 'Unifi - Kitchen AP'
      value_template: >-
        {% if is_state("device_tracker.unifi_kitchen_ap", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.unifi_kitchen_ap", "home") %}
          mdi:wifi
        {% else %}
          mdi:wifi-off
        {% endif %}


      ################################################
      ## Device Status - Router - Master
      ################################################

- platform: template
  sensors:
    status_router_master:
      friendly_name: 'Router - Master'
      value_template: >-
        {% if is_state("device_tracker.router_master", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.router_master", "home") %}
          mdi:wifi
        {% else %}
          mdi:wifi-off
        {% endif %}

      ################################################
      ## Device Status - Scentsy - Sonoff
      ################################################

- platform: template
  sensors:
    status_scentsy_sonoff:
      friendly_name: 'Scentsy Sonoff'
      value_template: >-
        {% if is_state("device_tracker.scentsy_sonoff", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.scentsy_sonoff", "home") %}
          mdi:wifi
        {% else %}
          mdi:wifi-off
        {% endif %}

      ################################################
      ## Device Status - Smartthings Hub
      ################################################

- platform: template
  sensors:
    status_smart_thing_hub:
      friendly_name: 'Smart Things Hub'
      value_template: >-
        {% if is_state("device_tracker.smart_thing_hub", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}

      ################################################
      ## Device Status - Sonos Bedroom
      ################################################

- platform: template
  sensors:
    status_sonos_bedroom:
      friendly_name: 'Sonos Bedroom'
      value_template: >-
        {% if is_state("device_tracker.sonos_bedroom", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.sonos_bedroom", "home") %}
          mdi:music-note
        {% else %}
          mdi:music-note-off
        {% endif %}

      ################################################
      ## Device Status - TV Living Room
      ################################################

- platform: template
  sensors:
    status_tv_living_room:
      friendly_name: 'TV - Living Room'
      value_template: >-
        {% if is_state("device_tracker.tv_living_room", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.tv_living_room", "home") %}
          mdi:television-classic
        {% else %}
          mdi:television-classic-off
        {% endif %}

      ################################################
      ## Device Status - Xiaomi Vacuum
      ################################################

- platform: template
  sensors:
    status_xiaomi_vacuum:
      friendly_name: 'Xiaomi Vacuum'
      value_template: >-
        {% if is_state("device_tracker.xiaomi_vacuum", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.xiaomi_vacuum", "home") %}
          mdi:broom
        {% else %}
          mdi:cancel
        {% endif %}

      ################################################
      ## Device Status - Living Room Scentsy
      ################################################

- platform: template
  sensors:
    status_living_room_scentsy:
      friendly_name: 'Living Room Scentsy'
      value_template: >-
        {% if is_state("device_tracker.sonoff_living_room_scentsy", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.sonoff_living_room_scentsy", "home") %}
          mdi:fire
        {% else %}
          mdi:cancel
        {% endif %}

      ################################################
      ## Device Status - Bedroom Scentsy
      ################################################

- platform: template
  sensors:
    status_bedroom_scentsy:
      friendly_name: 'Bedroom Scentsy'
      value_template: >-
        {% if is_state("device_tracker.sonoff_bedroom_screntsy", "home") %}
          Online
        {% else %}
          Offline
        {% endif %}
      icon_template: >-
        {% if is_state("device_tracker.sonoff_bedroom_screntsy", "home") %}
          mdi:fire
        {% else %}
          mdi:cancel
        {% endif %}

################################################
## Device Status - Group
################################################

group:

      ################################################
      ## Device Status -  Group - TV
      ################################################

  tv_status:
    name: TV Status
    control: hidden
    entities:
      - sensor.status_bedroom_rf
      - sensor.status_fire_tv_1
      - sensor.status_fire_tv_2
      - sensor.status_fire_tv_3
      # - sensor.status_tv_living_room

      ################################################
      ## Device Status -  Group - CCTV
      ################################################

  cctv_status:
    name: TV Status
    control: hidden
    entities:
      - sensor.status_hikvision_1
      - sensor.status_hikvision_2
      - sensor.status_hikvision_3
      - sensor.status_nest_camera

      ################################################
      ## Device Status -  Group - Server
      ################################################

  server_status:
    name: Server Status
    control: hidden
    entities:
      - sensor.status_router_master
      - sensor.status_unifi_kitchen_ap
      - sensor.status_network_extender
      - sensor.status_philips_hue_hub
      - sensor.status_smart_thing_hub

      ################################################
      ## Device Status -  Group - Google Home
      ################################################

  google_status:
    name: Google Home Status
    control: hidden
    entities:
      - sensor.status_google_home_bedroom
      - sensor.status_google_home_front_room
      - sensor.status_google_home_kitchen
      - sensor.status_google_home_living_room

      ################################################
      ## Device Status -  Group - Misc
      ################################################

  misc_status:
    name: Misc Status
    control: hidden
    entities:
      - sensor.status_jack_laptop
      - sensor.status_nest_thermostat
      - sensor.status_ps4
      - sensor.status_scentsy_sonoff
      - sensor.status_sonos_bedroom
      - sensor.status_xiaomi_vacuum
