################################################################
## Packages / doorbell
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'doorbell'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## doorbell
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## doorbell
################################################

automation:

      #################################################################
      ## doorbell - ring
      #################################################################

- alias: Door Input Boolean On
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.doorbell_ring

- alias: Door Input Boolean Off
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    from: 'on'
    to: 'off'
    for:
      seconds: 2
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.doorbell_ring

      #################################################################
      ## doorbell - ring
      #################################################################

- alias: Door Ring
  trigger:
    platform: state
    entity_id: input_boolean.doorbell_ring
    from: 'off'
    to: 'on'
  action:
    - service: script.google_notify
      data_template:
        message: 'Ding Dong!'


################################################
## doorbell
################################################

input_boolean:

      #################################################################
      ## doorbell - ring
      #################################################################

  doorbell_ring:
    name: Ring Ring
    initial: off
