################################################################
## Packages / Door Sensor
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Door Sensor'

      expose: &expose
        <<: *customize
        expose: false

    ################################################
    ## Door Sensor
    ################################################

    binary_sensor.door_sensor_bathroom:
      <<: *customize
      friendly_name: "Bathroom Door"
    binary_sensor.door_sensor_dishwasher:
      <<: *customize
      friendly_name: "Dishwasher Door"
    binary_sensor.door_sensor_front_door:
      <<: *customize
      friendly_name: "Front Door"
    binary_sensor.door_sensor_dressing_room_window:
      <<: *customize
      friendly_name: "Dressing Room Window"    

    ################################################
    ## Door Sensor Battery
    ################################################

    sensor.door_sensor_dishwasher:
      <<: *customize
      friendly_name: "Battery - Door Sensor - Dishwasher"

    sensor.door_sensor_bathroom:
      <<: *customize
      friendly_name: "Battery - Door Sensor - Bathroom"

    sensor.door_sensor_dressing_room_window:
      <<: *customize
      friendly_name: "Battery - Door Sensor - Dressing Room Window"


################################################
## Door Sensor - Binary Sensor's
################################################

binary_sensor:

      #################################################################
      ## Door Sensor - Front Door
      #################################################################

- platform: mqtt
  name: "Door Sensor Front Door"
  state_topic: "smartthings/Door Sensor - Front Door/contact/state"
  command_topic: "smartthings/Door Sensor - Front Door/contact/state"
  device_class: door
  payload_on: "open"
  payload_off: "closed"
  retain: true

      #################################################################
      ## Door Sensor - Bathroom
      #################################################################

- platform: mqtt
  name: "Door Sensor Bathroom"
  state_topic: "smartthings/Door Sensor - Bathroom/contact/state"
  command_topic: "smartthings/Door Sensor - Bathroom/contact/state"
  device_class: door
  payload_on: "open"
  payload_off: "closed"
  retain: true

      #################################################################
      ## Door Sensor - Dressing Room Window
      #################################################################

- platform: mqtt
  name: "Door Sensor Dressing Room Window"
  state_topic: "smartthings/Door Sensor - Dressing Room Window/contact/state"
  command_topic: "smartthings/Door Sensor - Dressing Room Window/contact/state"
  device_class: window
  payload_on: "open"
  payload_off: "closed"
  retain: true

################################################
## Door Sensor - Automation's
################################################

automation:

      #################################################################
      ## Door Sensor - Front Door - Hallway Light Automation On
      #################################################################

- alias: Hallway light front door
  trigger:
   - platform: state
     entity_id: binary_sensor.front_door
     from: 'off'
     to: 'on'
  action:
    service: light.turn_on
    entity_id: light.hallway_light

      #################################################################
      ## Door Sensor - Front Door - Hallway Light Automation Off
      #################################################################

- alias: Turn off hall light door close
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'on'
    to: 'off'
    for:
      seconds: 10
  action:
    service: light.turn_on
    entity_id: light.hallway_light

- alias: Dressing room window open home
  trigger:
    platform: time
    at: '19:00:00'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: binary_sensor.door_sensor_dressing_room_window
      state: 'on'
  action:
    service: script.google_notify
    data:
     message: 'Dressing Room Window is Open'


- alias: Dressing room window open not home
  trigger:
    platform: time
    at: '19:00:00'
  condition:
    - condition: state
      entity_id: group.family
      state: 'not_home'
    - condition: state
      entity_id: binary_sensor.door_sensor_dressing_room_window
      state: 'on'
  action:
    service: notify.pushover
    data:
     message: Close the Dressing Room Window so the cats don't escape!
     title: Urgent!

################################################
## Door Sensor - Sensor's
################################################

sensor:

      #################################################################
      ## Sensor - Battery - Dishwasher
      #################################################################

  - platform: mqtt
    name: battery_door_sensor_dishwasher
    state_topic: "smartthings/Door Sensor - Dishwasher/battery/state"
    device_class: battery
    unit_of_measurement: '%'

      #################################################################
      ## Sensor - Battery - Bathroom
      #################################################################

  - platform: mqtt
    name: battery_door_sensor_bathroom
    state_topic: "smartthings/Door Sensor - Bathroom/battery/state"
    device_class: battery
    unit_of_measurement: '%'

      #################################################################
      ## Sensor - Battery - Dressing Room Window
      #################################################################

  - platform: mqtt
    name: battery_door_sensor_dressing_room_window
    state_topic: "smartthings/Door Sensor - Dressing Room Window/battery/state"
    device_class: battery
    unit_of_measurement: '%'
