################################################################
## Packages / doorbell
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'doorbell'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## doorbell
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## doorbell
################################################

automation:

      #################################################################
      ## doorbell - ring
      #################################################################

- alias: Door Input Boolean On
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.doorbell_ring

- alias: Door Input Boolean Off
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    from: 'on'
    to: 'off'
    for:
      seconds: 1
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.doorbell_ring

      #################################################################
      ## doorbell - ring
      #################################################################

- alias: Door Ring
  trigger:
    platform: state
    entity_id: input_boolean.doorbell_ring
    from: 'off'
    to: 'on'
  action:
    - service: media_player.play_media
      data:
        entity_id:
         - media_player.bedroom_speaker
         - media_player.front_room_speaker
         - media_player.kitchen_speaker
         - media_player.living_room_speaker
        media_content_id: !secret doorbell
        media_content_type: 'music'


################################################
## doorbell
################################################

input_boolean:

      #################################################################
      ## doorbell - ring
      #################################################################

  doorbell_ring:
    name: Ring Ring
    initial: off
