################################################################
## Packages / Feed the Kittens
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Feed the Kittens'

      expose: &expose
        <<: *customize
        expose: true

      not-expose: &not-expose
        <<: *customize
        expose: false

    ################################################
    ## Feed the Kittens
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Feed the Kittens
################################################

automation:

##############################################################################
###  Audio notification to ramind us of kitten's food time
##############################################################################

- alias: Feed the kittens
  trigger:
    - platform: time
      at: '07:30:00'
    - platform: time
      at: '14:00:00'
    - platform: time
      at: '21:00:00'
  action:
    - service: script.google_notify
      data_template:
        message: 'Feed the Kittens!'
