################################################################
## Packages / Feed the Lara
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Feed the Lara'

      expose: &expose
        <<: *customize
        expose: true

      not-expose: &not-expose
        <<: *customize
        expose: false

    ################################################
    ## Feed the Lara
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Feed the Lara - Automation
################################################

automation:

    #################################################################
    ## Feed the kittens notification's
    #################################################################


- alias: Feed the Lara lunch
  trigger:
    - platform: time
      at: '12:30:00'
  action:
    - delay: '00:10:00'
    - service: tts.google_say
      entity_id:
        - media_player.bedroom_speaker
        - media_player.front_room_speaker
        - media_player.kitchen_speaker
        - media_player.living_room_speaker
      data:
        message: 'Feed the Laara!'
