################################################################
## Packages / Feed the Kittens
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Feed the Kittens'

      expose: &expose
        <<: *customize
        expose: true

      not-expose: &not-expose
        <<: *customize
        expose: false

    ################################################
    ## Feed the Kittens
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Feed the Kittens
################################################

automation:

##############################################################################
###  Audio notification to ramind us of kitten's food time
##############################################################################

- alias: Feed the kittens AM
  trigger:
    - platform: time
      at: '07:30:00'
    - platform: time
      at: '14:00:00'
    - platform: time
      at: '21:00:00'
  action:
    - service: tts.google_say
      entity_id:
        - media_player.bedroom_speaker
        - media_player.front_room_speaker
        - media_player.kitchen_speaker
        - media_player.living_room_speaker
      data:
        message: 'Feed the Kittens!'
