################################################################
## Packages / Media Player Default Volume
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Media Player Default Volume'

      expose: &expose
        <<: *customize
        expose: true

      not-expose: &not-expose
        <<: *customize
        expose: false

    ################################################
    ## Media Player Default Volume
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Media Player Default Volume
################################################

automation:

#################################################################
## Day Time Google Home Volume
#################################################################

- alias: Day Time Google Home Volume
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.bedroom_speaker
        - media_player.front_room_speaker
        - media_player.kitchen_speaker
        - media_player.living_room_speaker
        - media_player.shed_speaker
      data:
        volume_level: "0.45"

#################################################################
## Night Time Google Home Volume
#################################################################

- alias: Night Time Google Home Volume
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.bedroom_speaker
        - media_player.front_room_speaker
        - media_player.kitchen_speaker
        - media_player.living_room_speaker
        - media_player.shed_speaker
      data:
        volume_level: "0.09"
