################################################################
## Packages / Media Player Default Volume
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Media Player Default Volume'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## Media Player Default Volume
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Media Player Default Volume
################################################

automation:

      #################################################################
      ## Day Time Google Home Volume
      #################################################################

- alias: Day Time Google Home Volume
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: media_player.volume_set
      entity_id:
        # - media_player.bedroom_speaker
        - media_player.front_room_speaker
        - media_player.kitchen_speaker
        - media_player.living_room_speaker
        - media_player.shed_speaker
      data:
        volume_level: "0.25"

      #################################################################
      ## Night Time Google Home Volume
      #################################################################

- alias: Night Time Google Home Volume
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: media_player.volume_set
      entity_id:
        # - media_player.bedroom_speaker
        - media_player.front_room_speaker
        - media_player.kitchen_speaker
        - media_player.living_room_speaker
        - media_player.shed_speaker
      data:
        volume_level: "0.09"

      #################################################################
      ## Stop bedroom white noise in the morning
      #################################################################

- alias: stop white noise
  trigger:
    platform: time
    at: '06:45:00'
  action:
    - service: media_player.media_stop
      entity_id: media_player.bedroom_speaker
