################################################################
## Packages / Notify
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Notify'

      expose: &expose
        <<: *customize
        expose: true

      not-expose: &not-expose
        <<: *customize
        expose: false

    ################################################
    ## Notify
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Notify - Script
################################################

script:

    #################################################################
    ## Google Notify
    #################################################################

    google_notify:
      sequence:
       - condition: template
         value_template: '{{ message | trim != "" }}'
       - service: tts.google_say
         entity_id:
           - media_player.bedroom_speaker
           - media_player.front_room_speaker
           - media_player.kitchen_speaker
           - media_player.living_room_speaker
         data_template:
           message: "{{ message }}"

    google_notify_no_bedroom:
      sequence:
       - condition: template
         value_template: '{{ message | trim != "" }}'
       - service: tts.google_say
         entity_id:
           - media_player.front_room_speaker
           - media_player.kitchen_speaker
           - media_player.living_room_speaker
         data_template:
           message: "{{ message }}"

    #################################################################
    ## Voice Notify
    #################################################################

    voice_notify:
      sequence:
        # - condition: template
        #   value_template: '{{ states.input_boolean.voice_notifications.state == "on" }}'
        # - condition: template
        #   value_template: '{{ states.input_boolean.do_not_disturb.state | lower == "off" }}'
        # - condition: template
        #   value_template: '{{ states.media_player.gstreamer.state == "idle" }}'
        # - condition: template
        #   value_template: '{{ states.media_player.mpd.state != "playing" }}'
        - condition: template
          value_template: '{{ message | trim != "" }}'
        - condition: state
          entity_id: group.all_devices
          state: 'home'
        # - condition: template
        #   value_template: >
        #     {% if states.input_boolean.emergency_mode.state == "on" %}
        #       true
        #     {% else %}
        #       {{ states.group.all_devices.state == "home" }}
        #     {% endif %}
        - condition: template
          value_template: >
            {% if only_at_night | default('no', true ) == "yes" %}
              {% if states.sun.sun.state == "above_horizon" %}
                false
              {% else %}
                true
              {% endif %}
            {% else %}
              true
            {% endif %}
        - service: script.voice_greeting
          data_template:
            greeting: '{{ greeting }}'
        # - service: media_player.volume_set
        #   entity_id: media_player.gstreamer
        #   data_template:
        #     volume_level: >
        #       {% if states.input_boolean.emergency_mode.state == "on" %}
        #         0.9
        #       {% else %}
        #         {% if now().hour | int < 12 and now().hour | int > 6 %}
        #         0.5
        #         {% elif now().hour|int > 12 and now().hour|int < 20 %}
        #         0.9
        #         {% else %}
        #         0.3
        #         {% endif %}
        #       {% endif %}
        # - service: mqtt.publish
        #   data_template:
        #     topic: '/home/tts'
        #     retain: false
        #     payload: >-
        #       {% set msg = "" %}
        #       {%- macro getEndGreeting() -%}
        #         {%- if greeting |default('yes', true ) == "yes" -%}
        #           Thank you!
        #         {%- endif -%}
        #       {%- endmacro -%}
        #       {% set msg = msg + "<speak> " %}
        #       {% set msg = msg + ". " + message %}
        #       {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
        #       {% set msg = msg + " " + getEndGreeting() %}
        #       {% set msg = msg + " </speak>" %}
        #       {{ msg }}
        - service: tts.google_say
          data_template:
            entity_id:
              - media_player.bedroom_speaker
              - media_player.front_room_speaker
              - media_player.kitchen_speaker
              - media_player.living_room_speaker
            cache: true
            message: >
              {% set msg = "" %}
              {%- macro getEndGreeting() -%}
                {%- if greeting |default('yes', true ) == "yes" -%}
                  Thank you!
                {%- endif -%}
              {%- endmacro -%}
              {% set msg = msg + "<speak> " %}
              {% set msg = msg + ". " + message %}
              {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
              {% set msg = msg + " " + getEndGreeting() %}
              {% set msg = msg + " </speak>" %}
              {{ msg }}





    voice_greeting:
      sequence:
        - service: tts.google_say
          data_template:
            entity_id:
              - media_player.bedroom_speaker
              - media_player.front_room_speaker
              - media_player.kitchen_speaker
              - media_player.living_room_speaker
            cache: true
            message: >
              {% set msg = "" %}
              {% macro getGreeting() %}
                {% if greeting | default('yes', true ) == "yes" %}
                  {% if now().hour|int < 12 %}
                    Good morning.
                  {% elif now().hour|int < 18 %}
                    Good afternoon.
                  {% else %}
                    Good evening.
                  {% endif %}
                {% endif %}
              {% endmacro %}
              {% set msg = msg + "<speak> " %}
              {% set msg = msg + " " + getGreeting() %}
              {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
              {% set msg = msg + " </speak>" %}
              {{ msg }}
