################################################################
## Packages / Occupancy
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Occupancy'

      expose: &expose
        <<: *customize
        expose: true

      not-expose: &not-expose
        <<: *customize
        expose: false

    ################################################
    ## Occupancy
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Occupancy - Automations
################################################

automation:

      #################################################################
      ## Living Room Occupancy
      #################################################################

# - alias: Occupancy - Living turn on if motion detected
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_living_room_camera
#       from: 'off'
#       to: 'on'
#   action:
#     - service: input_boolean.turn_on
#       entity_id: input_boolean.living_occupancy

      #################################################################
      ## Reset Living Room Occupancy
      #################################################################

# - alias: Occupancy - Living turn off after 30min of no motion
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_living_room_camera
#       to: 'off'
#       for:
#         minutes: 30
#   action:
#     - service: input_boolean.turn_off
#       entity_id: input_boolean.living_occupancy

      #################################################################
      ## Kitchen Occupancy
      #################################################################

# - alias: Occupancy - Kitchen turn on if motion detected
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_kitchen_camera
#       from: 'off'
#       to: 'no'
#   action:
#     - service: input_boolean.turn_on
#       entity_id: input_boolean.kitchen_occupancy

      #################################################################
      ## Reset Kitchen Occupancy
      #################################################################
#
# - alias: Occupancy - Kitchen turn off after 30min of no motion
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.motion_kitchen_camera
#       to: 'off'
#       for:
#         minutes: 30
#   action:
#     - service: input_boolean.turn_off
#       entity_id: input_boolean.kitchen_occupancy

# - alias: Bedroom Idle
#   trigger:
#   - entity_id: binary_sensor.motion_bedroom
#     for:
#       minutes: 30
#     from: 'On'
#     platform: state
#     to: 'Off'
#   action:
#   - data:
#       entity_id: input_boolean.bedroom_idle
#     service: input_boolean.turn_on
#
# - alias: Living Room Idle
#   trigger:
#   - entity_id: binary_sensor.motion_living_room
#     for:
#       minutes: 30
#     from: 'On'
#     platform: state
#     to: 'Off'
#   action:
#   - data:
#       entity_id: input_boolean.living_room_idle
#     service: input_boolean.turn_on

      #################################################################
      ## input_boolean bedroom off
      #################################################################

- alias: 'Bathroom Occupany Off'
#Trigger
  trigger:
    platform: state
    entity_id: binary_sensor.motion_bedroom
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  condition:
    - condition: state
      entity_id: binary_sensor.door_sensor_bathroom
      state: 'off'
  action:
  - data:
      entity_id: input_boolean.bathroom_occupancy
    service: input_boolean.turn_off


      #################################################################
      ## input_boolean bathroom on
      #################################################################

- alias: 'Bathroom Occupany On'
#Trigger
  trigger:
    platform: state
    entity_id: binary_sensor.door_sensor_bathroom
    from: 'on'
    to: 'off'
  condition:
    - condition: state
      entity_id: light.bathroom_lights
      state: 'off'
  action:
  - data:
      entity_id: input_boolean.bathroom_occupancy
    service: input_boolean.turn_on

################################################
## Occupancy - Input Boolean
################################################

input_boolean:

      #################################################################
      ## Living Room Occupancy
      #################################################################

  living_occupancy:
    name: Living Occupancy
    initial: off
    icon: mdi:account

      #################################################################
      ## Kitchen Occupancy
      #################################################################

  kitchen_occupancy:
    name: Kitchen Occupancy
    initial: off
    icon: mdi:account

      #################################################################
      ## Bathroom Occupancy
      #################################################################

  bathroom_occupancy:
    name: Bathroom Occupancy
    initial: off
    icon: mdi:account


      #################################################################
      ## Living Room Idle
      #################################################################

  living_room_idle:
    name: Living Room Idle
    initial: off
    icon: mdi:account
