################################################################
## Packages / Pi_Hole
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Pi_Hole'

      expose: &expose
        <<: *customize
        expose: false

    ################################################
    ## Pi_Hole
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Pi_Hole - Sensor
################################################

# sensor:

      #################################################################
      ## Add Component
      #################################################################

  # - platform: pi_hole
  #   host: !secret pi_hole_host
  #   location: admin
  #   ssl: false
