################################################################
## Packages / Pi_Hole
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Pi_Hole'

      expose: &expose
        <<: *customize
        expose: false

    ################################################
    ## Pi_Hole
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Pi_Hole - Sensor
################################################

sensor:

      #################################################################
      ## Add Component
      #################################################################

  - platform: pi_hole
    host: 192.168.1.157
    ssl: false
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today
      - domains_being_blocked
      - queries_cached
      - queries_forwarded
      - unique_clients
      - unique_domains
