################################################################
## Packages / Playstation
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Playstation'

      expose: &expose
        <<: *customize
        expose: false

    ################################################
    ## Playstation
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Playstation - Media Player's
################################################

media_player:

      #################################################################
      ## Playstation
      #################################################################

#- platform: ps4
#  host: http://0.0.0.0:3031
#  ps4_ip: 192.168.1.252
#  name: PlayStation 4
#  local_store: games
