################################################################
## Packages / Power Monitor
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Lights'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## Power Monitor
    ################################################

    sensor.power_perfect_prep:
      <<: *expose

    sensor.power_dish_washer:
      <<: *expose

################################################
## Power Monitor - Automation's
################################################

automation:

      #################################################################
      ## Perfect Prep Lights Up
      #################################################################

# - alias: Perfect Prep Lights Up
#   trigger:
#     platform: numeric_state
#     entity_id: 'sensor.power_perfect_prep'
#     above: '0.9'
#   condition:
#     condition: time
#     after: "22:45:00"
#     before: "06:00:00"
#   action:
#     - service: light.turn_on
#       entity_id: light.lara_bedside_light
#       data_template:
#         brightness: '{{states.light.lara_bedside_light.attributes.brightness|int + 30}}'

        #################################################################
        ## Perfect Prep Lights Down
        #################################################################

# - alias: Perfect Prep Lights Down
#   trigger:
#     platform: numeric_state
#     entity_id: 'sensor.power_perfect_prep'
#     below: '1.0'
#     for:
#      minutes: 3
#   condition:
#     condition: time
#     after: "22:45:00"
#     before: "06:00:00"
#   action:
#     - service: light.turn_on
#       entity_id: light.lara_bedside_light
#       data_template:
#         brightness: '{{states.light.lara_bedside_light.attributes.brightness|int - 30}}'


################################################
## Power Monitor - Sensor
################################################

sensor:

      #################################################################
      ## MQTT Monitor of power usage - Perfect Prep
      #################################################################

# - platform: mqtt
#   name: "Power Perfect Prep"
#   state_topic: "smartthings/Perfect Prep/power/state"
#   unit_of_measurement: "kw"

      #################################################################
      ## MQTT Monitor of power usage - Dish Washer
      #################################################################

- platform: mqtt
  name: "Power Dish Washer"
  # value_template: '{{ value | default (0) }}'
  # value_template: >-
  #   {% if is_state("sensor.power_dish_washer", "unknown") %}
  #     0
  #   {% else %}
  #     '{{ value }}'
  #   {% endif %}
  state_topic: "smartthings/Power Dish Washer/power/state"
  unit_of_measurement: "kw"


################################################
## Perfect Prep - Switches
################################################

switch:

      #################################################################
      ## MQTT Power Control
      #################################################################

- platform: mqtt
  name: "Perfect Prep"
  state_topic: "smartthings/Power Perfect Prep/switch/state"
  command_topic: "smartthings/Power Perfect Prep/switch/set"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  optimistic: false
  retain: false
