################################################################
## Packages / Power Monitor
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Lights'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## Power Monitor
    ################################################

    sensor.power_perfect_prep:
      <<: *expose

    sensor.power_dish_washer:
      <<: *expose

################################################
## Power Monitor - Automation's
################################################

automation:

      #################################################################
      ## Turn on humidifier
      #################################################################

  - alias: humidifier on
    trigger:
      platform: time
      at: '22:30:00'
    action:
      - service: switch.turn_on
        entity_id: switch.power_bedroom_humidifier

      #################################################################
      ## Turn off humidifier
      #################################################################

  - alias: humidifier off
    trigger:
      platform: time
      at: '07:30:00'
    action:
      - service: switch.turn_off
        entity_id: switch.power_bedroom_humidifier


      #################################################################
      ## Turn on vapor
      #################################################################

  - alias: vapor on
    trigger:
      platform: time
      at: '00:30:00'
    action:
      - service: switch.turn_on
        entity_id: switch.power_bedroom_vapor

      #################################################################
      ## Turn off vapor
      #################################################################

  - alias: vapor off
    trigger:
      platform: time
      at: '04:30:00'
    action:
      - service: switch.turn_off
        entity_id: switch.power_bedroom_vapor

        #################################################################
        ## Perfect Prep Lights Up
        #################################################################

# - alias: Perfect Prep Lights Up
#   trigger:
#     platform: numeric_state
#     entity_id: 'sensor.power_perfect_prep'
#     above: '0.9'
#   condition:
#     condition: time
#     after: "22:45:00"
#     before: "06:00:00"
#   action:
#     - service: light.turn_on
#       entity_id: light.lara_bedside_light
#       data_template:
#         brightness: '{{states.light.lara_bedside_light.attributes.brightness|int + 30}}'

        #################################################################
        ## Perfect Prep Lights Down
        #################################################################

# - alias: Perfect Prep Lights Down
#   trigger:
#     platform: numeric_state
#     entity_id: 'sensor.power_perfect_prep'
#     below: '1.0'
#     for:
#      minutes: 3
#   condition:
#     condition: time
#     after: "22:45:00"
#     before: "06:00:00"
#   action:
#     - service: light.turn_on
#       entity_id: light.lara_bedside_light
#       data_template:
#         brightness: '{{states.light.lara_bedside_light.attributes.brightness|int - 30}}'


################################################
## Power Monitor - Sensor
################################################

sensor:

      #################################################################
      ## MQTT Monitor of power usage - Bedroom Humidifier
      #################################################################

- platform: mqtt
  name: "Power Bedroom Humidifier"
  state_topic: "smartthings/Power - Bedroom Humidifier/power/state"
  unit_of_measurement: "kw"

################################################
## Power - Switches
################################################

switch:

      #################################################################
      ## MQTT Power Control
      #################################################################

- platform: mqtt
  name: "Power Bedroom Humidifier"
  state_topic: "smartthings/Power - Bedroom Humidifier/switch/state"
  command_topic: "smartthings/Power - Bedroom Humidifier/switch/set"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  optimistic: false
  retain: false

- platform: mqtt
  name: "Power Bedroom Vapor"
  state_topic: "smartthings/Power - Bedroom Vapor/switch/state"
  command_topic: "smartthings/Power - Bedroom Vapor/switch/set"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  optimistic: false
  retain: false

