################################################################
## Packages / presence detection
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Presence Detection'

      expose: &expose
        <<: *customize
        expose: false

    ################################################
    ## Presence Detection
    ################################################

    sensor.jack_status:
      <<: *customize
      entity_picture: /local/jack.jpg

    sensor.lara_status:
      <<: *customize
      entity_picture: /local/lara.jpg

    sensor.presence_sensor_jack_car:
      <<: *customize
      friendly_name: "Battery - Presence Sensor - Jack Car"

    sensor.presence_sensor_lara_car:
      <<: *customize
      friendly_name: "Battery - Presence Sensor - Lara Car"

################################################
## Presence Detection - Input Select
################################################


input_select:

      #################################################################
      ## Jack Status
      #################################################################

  jack_status_dropdown:
    name: Jack
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

      #################################################################
      ## Lara Status
      #################################################################

  lara_status_dropdown:
    name: Lara
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home



################################################
## Presence Detection - Sensor
################################################

sensor:

      #################################################################
      ## Jack Status
      #################################################################

  - platform: template
    sensors:
      jack_status:
        value_template: '{{ states.input_select.jack_status_dropdown.state }}'
        friendly_name: 'Jack'

      #################################################################
      ## Lara Status
      #################################################################

  - platform: template
    sensors:
      lara_status:
        value_template: '{{ states.input_select.lara_status_dropdown.state }}'
        friendly_name: 'Lara'

      ################################################
      ##  Sensor - Battery - Presence Jack Car
      ################################################

  - platform: mqtt
    name: battery_presence_sensor_jack_car
    state_topic: "smartthings/Presence Jack Car/battery/state"
    device_class: battery
    unit_of_measurement: '%'

      ################################################
      ##  Sensor - Battery - Presence Lara Car
      ################################################

  - platform: mqtt
    name: battery_presence_sensor_lara_car
    state_topic: "smartthings/Presence Lara Car/battery/state"
    device_class: battery
    unit_of_measurement: '%'

################################################
## Presence Detection - Automation
################################################

automation:

      #################################################################
      ## Jack arrived
      #################################################################
- alias: Mark person as just arrived
  trigger:
    - platform: state
      entity_id: binary_sensor.jack_home
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.lara_home
      from: 'off'
      to: 'on'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'binary_sensor.jack_home' %}
            input_select.jack_status_dropdown
          {% else %}
            input_select.lara_status_dropdown
          {% endif %}
        option: >
          {% if trigger.entity_id == 'binary_sensor.jack_home' %}
            {% if states.input_select.jack_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% else %}
            {% if states.input_select.lara_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% endif %}


- alias: Mark person as home
  trigger:
    - platform: state
      entity_id: input_select.jack_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.lara_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.jack_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.lara_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.jack_status_dropdown' %}
            input_select.jack_status_dropdown
          {% else %}
            input_select.lara_status_dropdown
          {% endif %}
        option: Home

- alias: Mark person as just left
  trigger:
    - platform: state
      entity_id: binary_sensor.jack_home
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.lara_home
      from: 'on'
      to: 'off'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'binary_sensor.jack_home' %}
            input_select.jack_status_dropdown
          {% else %}
            input_select.lara_status_dropdown
          {% endif %}
        option: Just Left

- alias: Mark person as away
  trigger:
    - platform: state
      entity_id: input_select.jack_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.lara_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.jack_status_dropdown' %}
            input_select.jack_status_dropdown
          {% else %}
            input_select.lara_status_dropdown
          {% endif %}
        option: Away

- alias: Mark person as extended away
  trigger:
    - platform: state
      entity_id: input_select.jack_status_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.lara_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.jack_status_dropdown' %}
            input_select.jack_status_dropdown
          {% else %}
            input_select.lara_status_dropdown
          {% endif %}
        option: Extended Away

################################################
## device_tracker
################################################

device_tracker:

  ################################################
  ## tile
  ################################################


  - platform: tile
    username: !secret tile_user
    password: !secret tile_password
