################################################################
## Packages / Pushover
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Pushover'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## Pushover
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Notify - pushover
################################################

notify:

      #################################################################
      ## Pushover - credentials
      #################################################################

  - name: pushover
    platform: pushover
    api_key: !secret pushover_api
    user_key: !secret pushover_user

################################################
## Automation - pushover
################################################

automation:

      #################################################################
      ## Pushover - credentials
      #################################################################

- alias: plants need watering
  trigger:
   - platform: numeric_state
     entity_id: sensor.plant_bathroom_moisture
     below: 28
  action:
   - service: notify.pushover
     data:
       message: Your plants really need a water, there getting very dry!
       title: Urgent Plant Care
