################################################################
## Packages / Scentsy
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Scentsy'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## Scentsy
    ################################################

    switch.scentsy_bedroom:
      <<: *expose
      friendly_name: Bedroom Scentsy
      entity_picture: /local/scentsy-logo.png

    switch.living_room_scentsy_relay:
      <<: *expose
      friendly_name: Living Room Scentsy
      entity_picture: /local/scentsy-logo.png




################################################
## Scentsy - Switches
################################################

switch:

      #################################################################
      ## Scentsy - Living Room
      #################################################################

- platform: mqtt
  name: "Scentsy Living Room"
  state_topic: "stat/livingroom_scentsy/POWER"
  command_topic: "cmnd/livingroom_scentsy/power"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 0
  optimistic: false
  retain: true

      #################################################################
      ## Scentsy - Bedroom
      #################################################################

- platform: mqtt
  name: "Scentsy Bedroom"
  state_topic: "stat/bedroom_scentsy/POWER"
  command_topic: "cmnd/bedroom_scentsy/power"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 0
  optimistic: false
  retain: true

################################################
## Scentsy - Automation's
################################################

automation:

      #################################################################
      ## Scentsy - Bedroom Automation On
      #################################################################

- alias: bedroom scentsy on
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.scentsy_bedroom

      #################################################################
      ## Scentsy - Bedroom Automation Off
      #################################################################

- alias: bedroom scentsy off
  trigger:
    platform: time
    at: '03:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.scentsy_bedroom
