################################################################
## Packages / Sonos
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Sonos'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## Sonos
    ################################################

    # media_player.kitchen:
    #   <<: *customize
    #   friendly_name: Kitchen Sonos
    #   entity_picture: ''

################################################
## Sonos - Media Player's
################################################

media_player:

      #################################################################
      ## Sonos
      #################################################################

# - platform: sonos
#   hosts:
#    - 192.168.1.250
#    - 192.168.1.131

################################################
## Sonos - script's
################################################

script:

      #################################################################
      ## Sonos Say
      #################################################################

  sonos_say:
    alias: "Sonos TTS script"
    sequence:
     - service: media_player.sonos_snapshot
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.sonos_unjoin
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ sonos_entity }}"
         volume_level: "{{ volume }}"
     - service: tts.google_say
       data_template:
         entity_id: "{{ sonos_entity }}"
         message: "{{ message }}"
     - delay: "{{ delay }}"
     - service: media_player.sonos_restore
       data_template:
         entity_id: "{{ sonos_entity }}"
