################################################################
## Packages / System
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'System'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## System
    ################################################

    sensor.disk_free_:
      <<: *expose

    sensor.memory_use_percent:
      <<: *expose

    sensor.memory_use:
      <<: *expose

    sensor.memory_free:
      <<: *expose

    sensor.processor_use:
      <<: *expose

    sensor.last_boot:
      <<: *expose

################################################
## System - sensor
################################################

sensor:
      #################################################################
      ## System Monitor
      #################################################################

  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: processor_use
      - type: last_boot


      ################################################
      ## Time - Sensor
      ################################################


  - platform: time_date
    display_options:
      - 'time'
      - 'date'

################################################
## System - group
################################################

group:
      #################################################################
      ## System Group
      #################################################################

  system_monitor:
    entities:
      - sensor.disk_free_
      - sensor.memory_use_percent
      - sensor.memory_use
      - sensor.memory_free
      - sensor.processor_use
      - sensor.last_boot

################################################
## System - MQTT
################################################

mqtt:

      #################################################################
      ## MQTT - api pass
      #################################################################

  broker: 192.168.1.123
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass

################################################
## System - Custom_updater
################################################

custom_updater:
  track:
    - components
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json