################################################################
## Packages / Tile
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Tile'

      expose: &expose
        <<: *customize
        expose: false


    ################################################
    ## Tile
    ################################################

    # zone.home:
    #   <<: *customize
    #   friendly_name: "Home"



################################################
## device_tracker
################################################

device_tracker:
  - platform: tile
    username: !secret tile_user
    password: !secret tile_password
