################################################################
## Packages / Time
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Time'

      expose: &expose
        <<: *customize
        expose: false


    ################################################
    ## Time
    ################################################

    # zone.home:
    #   <<: *customize
    #   friendly_name: "Home"



################################################
## Time
################################################

sensor:

      ################################################
      ## Time - Sensor
      ################################################


- platform: time_date
  display_options:
    - 'time'
