################################################################
## Packages / Todoist
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Todoist'

      expose: &expose
        <<: *customize
        expose: false

    ################################################
    ## Todoist
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Todoist
################################################


# calendar:
#   - platform: todoist
#     token: !secret todoist_api
