################################################################
## Packages / Travel Times
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Travel Times'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true


    ################################################
    ## Travel Times
    ################################################

    # sensor.waze_travel_time	:
    #   <<: *expose

################################################
## Travel Times - Sensor's
################################################

sensor:

      #################################################################
      ## Google Travel Time api
      #################################################################

# - platform: google_travel_time
#   name: Jack Home To Work
#   api_key: !secret google_travel_api
#   origin: !secret origin
#   destination: !secret destination

      #################################################################
      ## Waze Travel Time api
      #################################################################

- platform: waze_travel_time
  name: Jack Home To Work
  origin: !secret origin
  destination: !secret destination
  region: 'EU'


################################################
## Travel Times - Group
################################################

group:

      #################################################################
      ## Travel Time Card
      #################################################################

  time_travel_card:
    name: Time To Destination
    entities:
      - sensor.waze_travel_time
