################################################################
## Packages / vacuum
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'vacuum'

      expose: &expose
        <<: *customize
        expose: false

    ################################################
    ## vacuum
    ################################################

    vacuum.vacuum_vacuum_cleaner:
      <<: *customize
      friendly_name: "Bob"

################################################
## Vacuum
################################################

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip
    token: !secret vacuum_token
