################################################################
## Packages / Weather
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Weather'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## Weather
    ################################################

    sensor.dark_sky_summary:
      friendly_name: Current Weather
      <<: *expose

    sensor.dark_sky_temperature:
      friendly_name: Current Temperature
      <<: *expose

    script.upstairs_tv_power:
      friendly_name: TV Power
      icon: mdi:power
      <<: *expose

    script.upstairs_tv_up:
      friendly_name: Volume Up
      icon: mdi:volume-high
      <<: *expose

    script.upstairs_tv_down:
      friendly_name: Volume Down
      icon: mdi:volume-medium
      <<: *expose

    script.living_room_tv_power:
      friendly_name: TV Power
      icon: mdi:power
      <<: *expose

    script.living_room_tv_up:
      friendly_name: Volume Up
      icon: mdi:volume-high
      <<: *expose

    script.living_room_tv_down:
      friendly_name: Volume Down
      icon: mdi:volume-medium
      <<: *expose

################################################
## Weather - Sensor's
################################################

sensor:

      #################################################################
      ## Yr
      #################################################################


- platform: yr
  name: Weather
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

      #################################################################
      ## DarkSky
      #################################################################

- platform: darksky
  api_key: !secret dark_sky_api
  units: uk2
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - hourly_summary
    - temperature
    - precip_probability
    - wind_speed
    - temperature_min

      #################################################################
      ## History Sensor
      #################################################################

- platform: statistics
  entity_id: sensor.weather_precipitation
  name: Rain Average
  sampling_size: 2000

################################################
## Weather - Group
################################################

group:

      #################################################################
      ## Weather Card
      #################################################################

  weather_card:
    name: Weather
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
