################################################################
## Packages / Weblinks
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Weblinks'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## Bathroom Lights
    ################################################

    # light.bathroom_light_1:
    #   <<: *not-expose
    #   friendly_name: "Bathroom Light 1"

#################################################################
## Weblinks - entities
#################################################################
weblink:
  entities:

      #################################################################
      ## Github Repo
      #################################################################

  - name: Repo
    url: https://github.com/jackjohnsonuk/Home-AssistantConfig
    icon: mdi:github-box

      #################################################################
      ## Plex
      #################################################################

  - name: Plex
    url: !secret plex_url
    icon: mdi:movie

      #################################################################
      ## Sonarr
      #################################################################

  - name: Sonarr
    url: !secret sonarr_url
    icon: mdi:radar

      #################################################################
      ## Radarr
      #################################################################

  - name: Radarr
    url: !secret radarr_url
    icon: mdi:radar

      #################################################################
      ## Sabnzbd
      #################################################################

  - name: Sabnzbd
    url: !secret sabnzbd_url
    icon: mdi:download

      #################################################################
      ## Octoprint
      #################################################################

  - name: Octoprint
    url: !secret octoprint_url
    icon: mdi:printer-3d

      #################################################################
      ## Router
      #################################################################

  - name: Router
    url: !secret router_url
    icon: mdi:router-wireless
